Update auto_deploy_on_push.yml

diff --git a/.github/workflows/auto_deploy_on_push.yml b/.github/workflows/auto_deploy_on_push.yml
--- a/.github/workflows/auto_deploy_on_push.yml
+++ b/.github/workflows/auto_deploy_on_push.yml
@@ -25,12 +25,12 @@ jobs:
         
     - name: Verify repository contents
       run: |
-        ls -la /home/runner/work/DM-MAP/DM-MAP
-        test -f /home/runner/work/DM-MAP/DM-MAP/package.json || (echo "package.json not found!" && exit 1)
+        ls -la /home/runner/work/DM-MAP/
+        test -f /home/runner/work/DM-MAP/package.json || (echo "package.json not found!" && exit 1)
 
     - name: Install dependencies
       run: |
-        cd /home/runner/work/DM-MAP/dm-map  # Ensure correct directory
+        cd /home/runner/work/DM-MAP  # Ensure correct directory
         npm install  # Install dependencies
         
     - name: SSH into server and deploy
