Update auto_deploy_on_push.yml

diff --git a/.github/workflows/auto_deploy_on_push.yml b/.github/workflows/auto_deploy_on_push.yml
--- a/.github/workflows/auto_deploy_on_push.yml
+++ b/.github/workflows/auto_deploy_on_push.yml
@@ -22,11 +22,17 @@ jobs:
       uses: actions/setup-node@v2
       with:
         node-version: '16'  # Specify the version of Node.js
+        
+    - name: Verify repository contents
+      run: |
+        ls -la /home/runner/work/DM-MAP/DM-MAP
+        test -f /home/runner/work/DM-MAP/DM-MAP/package.json || (echo "package.json not found!" && exit 1)
 
     - name: Install dependencies
       run: |
         cd /home/runner/work/DM-MAP/dm-map  # Ensure correct directory
         npm install  # Install dependencies
+        
     - name: SSH into server and deploy
       uses: appleboy/ssh-action@v0.1.0  # Use SSH action to connect to your server
       with:
